server:
  servlet:
    context-path: /
  port: 8085

spring:
  application:
    name: spring-loadbalancer-gateway
  profiles:
    active:
      -default:
  
  cloud:
    gateway:
      routes:
        - id: spring-loadbalancer-service-1
          uri: http://localhost:8081/service1
          predicates:
            - Path= /service1/employee/**
          filters:
            - AddRequestHeader=first-request, first-request-header
            - AddResponseHeader=first-response, first-response-header
        - id: spring-loadbalancer-service-2
          uri: http://localhost:8082/service2
          predicates:
            - Path= /service2/consumer/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
management:
  tracing:
    sampling:
      probability=0.1
logging:
  pattern:
    level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
    